### ISSUE TITLE
go v1.14 support

### ISSUE THREAD

**Issue by d7561985** [tarndt/wasmws#11]
compile issue:
`../../../go/pkg/mod/github.com/tarndt/wasmws@v0.0.0-20191230183838-0f186a886e92/websock_js.go:33:13: invalid operation: newBlob == jsUndefined (struct containing [0]func() cannot be compared)
../../../go/pkg/mod/github.com/tarndt/wasmws@v0.0.0-20191230183838-0f186a886e92/websock_js.go:39:46: invalid operation: testBlob.Get("arrayBuffer") != jsUndefined (struct containing [0]func() cannot be compared)
../../../go/pkg/mod/github.com/tarndt/wasmws@v0.0.0-20191230183838-0f186a886e92/websock_js.go:40:26: invalid operation: testBlob.Get("stream") != js.Undefined() (struct containing [0]func() cannot be compared)
`

golang developers specially has been added uncomparable state:
`// Value represents a JavaScript value. The zero value is the JavaScript value "undefined".
// Values can be checked for equality with the Equal method.
type Value struct {
	_     [0]func() // uncomparable; to make == not compile
	ref   ref       // identifies a JavaScript value, see ref type
	gcPtr *ref      // used to trigger the finalizer when the Value is not referenced any more
}
`

**Comment by tarndt** [comment]
Thanks for the bug report, will update soon

**Comment by joeblew99** [comment]
The PR sitting in the queue seems to fix this "equals" bug.

**Comment by joeblew99** [comment]
this is the link : https://github.com/tarndt/wasmws/pull/12

**Comment by tarndt** [comment]
Thanks @d7561985  and @joeblew99 , this has been resolved in https://github.com/tarndt/wasmws/pull/15
